── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1 
✔ readr   2.1.2      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Registered S3 method overwritten by 'hoardr':
  method           from
  print.cache_info httr
Loading required package: R6

Attaching package: ‘lightgbm’

The following object is masked from ‘package:dplyr’:

    slice

Error in `filter()`:
! Problem while computing `..1 = !(id %in% city_station_pair$station)`.
Caused by error in `match()`:
! 'match' requires vector arguments
Backtrace:
     ▆
  1. ├─temp_station %>% ...
  2. ├─dplyr::filter(., !(id %in% city_station_pair$station))
  3. ├─dplyr:::filter.data.frame(., !(id %in% city_station_pair$station))
  4. │ └─dplyr:::filter_rows(.data, ..., caller_env = caller_env())
  5. │   └─dplyr:::filter_eval(dots, mask = mask, error_call = error_call)
  6. │     ├─base::withCallingHandlers(...)
  7. │     └─mask$eval_all_filter(dots, env_filter)
  8. ├─id %in% city_station_pair$station
  9. └─base::.handleSimpleError(...)
 10.   └─dplyr (local) h(simpleError(msg, call))
 11.     └─rlang::abort(bullets, call = error_call, parent = skip_internal_condition(e))
Execution halted
